const ADD_INGREDIENT='ADD_INGREDINET'
const REMOVE_INGREDIENT='REMOVE_INGREDIENT'
const AUTH_SUCCESS='AUTH_SUCCESS'
export default {ADD_INGREDIENT,
                REMOVE_INGREDIENT,
                AUTH_SUCCESS}